### ISSUE TITLE
Expose Anchors

### ISSUE THREAD

**Issue by jakobhellermann** [saphyr-rs/saphyr#7]
I'm parsing `.unity` yaml files, which contain multiple documents like this
```yaml
--- !u!114 &71353
MonoBehaviour:
  m_ObjectHideFlags: 0
  m_CorrespondingSourceObject: {fileID: 0}
  m_PrefabInstance: {fileID: 0}
```
where the `&71353` is the id of the object.

As far as I can tell, the anchor is not exposed, right? The `yaml_loader` contains an `anchor_map` and `doc_stack` which contain `anchor_id`s but there's no way to get to that.
